"""cree les tables jobs et leurs agregats

Revision ID: eb214c0d03b9
Revises:
Create Date: 2026-08-05 09:58:13.936401
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Les types personnalisés du projet sont rendus par Alembic avec leur chemin
# complet : sans cet import, la migration lève un NameError à l'exécution.
import traffic_analysis.core.db.types

revision: str = "eb214c0d03b9"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "jobs",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("model_id", sa.String(length=64), nullable=False),
        sa.Column("file_name", sa.String(length=255), nullable=False),
        sa.Column("file_size_bytes", sa.Integer(), nullable=False),
        sa.Column("config_json", sa.JSON(), nullable=False),
        sa.Column("progress", sa.Float(), nullable=False),
        sa.Column("processed_frames", sa.Integer(), nullable=False),
        sa.Column("total_frames", sa.Integer(), nullable=False),
        sa.Column("processing_fps", sa.Float(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("video_width", sa.Integer(), nullable=False),
        sa.Column("video_height", sa.Integer(), nullable=False),
        sa.Column("video_fps", sa.Float(), nullable=False),
        sa.Column("video_frame_count", sa.Integer(), nullable=False),
        sa.Column("video_duration_ms", sa.Float(), nullable=False),
        sa.Column("stats_json", sa.JSON(), nullable=True),
        sa.Column("unique_vehicles", sa.Integer(), nullable=False),
        sa.Column("crossings_total", sa.Integer(), nullable=False),
        sa.Column("reid_hits", sa.Integer(), nullable=False),
        sa.Column("result_path", sa.String(length=512), nullable=True),
        sa.Column(
            "started_at", traffic_analysis.core.db.types.UtcDateTime(length=32), nullable=True
        ),
        sa.Column(
            "finished_at", traffic_analysis.core.db.types.UtcDateTime(length=32), nullable=True
        ),
        sa.Column(
            "created_at", traffic_analysis.core.db.types.UtcDateTime(length=32), nullable=False
        ),
        sa.Column(
            "updated_at", traffic_analysis.core.db.types.UtcDateTime(length=32), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_jobs_model_id"), ["model_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_jobs_status"), ["status"], unique=False)
        batch_op.create_index("ix_jobs_status_created", ["status", "created_at"], unique=False)

    op.create_table(
        "job_crossings",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("job_id", sa.String(length=32), nullable=False),
        sa.Column("line_id", sa.String(length=64), nullable=False),
        sa.Column("global_id", sa.Integer(), nullable=False),
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(length=32), nullable=False),
        sa.Column("direction", sa.Integer(), nullable=False),
        sa.Column("timestamp_ms", sa.Float(), nullable=False),
        sa.Column("frame_index", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("job_crossings", schema=None) as batch_op:
        batch_op.create_index("ix_job_crossings_line", ["job_id", "line_id"], unique=False)
        batch_op.create_index("ix_job_crossings_time", ["job_id", "timestamp_ms"], unique=False)

    op.create_table(
        "job_vehicles",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("job_id", sa.String(length=32), nullable=False),
        sa.Column("global_id", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(length=32), nullable=False),
        sa.Column("first_seen_ms", sa.Float(), nullable=False),
        sa.Column("last_seen_ms", sa.Float(), nullable=False),
        sa.Column("reid_count", sa.Integer(), nullable=False),
        sa.Column("avg_speed_px_s", sa.Float(), nullable=True),
        sa.Column("avg_speed_kmh", sa.Float(), nullable=True),
        sa.Column("best_plate_score", sa.Float(), nullable=True),
        sa.Column("zones_visited_json", sa.JSON(), nullable=False),
        sa.Column("crossed_lines_json", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("job_vehicles", schema=None) as batch_op:
        batch_op.create_index("ix_job_vehicles_label", ["job_id", "label"], unique=False)
        batch_op.create_index("uq_job_vehicles_identity", ["job_id", "global_id"], unique=True)

    op.create_table(
        "job_zone_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("job_id", sa.String(length=32), nullable=False),
        sa.Column("zone_id", sa.String(length=64), nullable=False),
        sa.Column("global_id", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(length=32), nullable=False),
        sa.Column("timestamp_ms", sa.Float(), nullable=False),
        sa.Column("frame_index", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("job_zone_events", schema=None) as batch_op:
        batch_op.create_index("ix_job_zone_events_zone", ["job_id", "zone_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("job_zone_events", schema=None) as batch_op:
        batch_op.drop_index("ix_job_zone_events_zone")

    op.drop_table("job_zone_events")
    with op.batch_alter_table("job_vehicles", schema=None) as batch_op:
        batch_op.drop_index("uq_job_vehicles_identity")
        batch_op.drop_index("ix_job_vehicles_label")

    op.drop_table("job_vehicles")
    with op.batch_alter_table("job_crossings", schema=None) as batch_op:
        batch_op.drop_index("ix_job_crossings_time")
        batch_op.drop_index("ix_job_crossings_line")

    op.drop_table("job_crossings")
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_index("ix_jobs_status_created")
        batch_op.drop_index(batch_op.f("ix_jobs_status"))
        batch_op.drop_index(batch_op.f("ix_jobs_model_id"))

    op.drop_table("jobs")
    # ### end Alembic commands ###
