"""ajoute le code d erreur du job

Revision ID: 209be6775284
Revises: c3ae6ba3917c
Create Date: 2026-08-07 12:36:50.832876

`error_code` accompagne le `error` déjà présent, pour la même raison qu'`AppError`
porte les deux : le message français se réécrit sans casser de client, le code non.
C'est lui qui permet à l'interface de proposer l'action correspondant à l'échec —
« précharger « X » puis relancer » — au lieu de faire une correspondance sur du texte.

`String(64)` et non `Text` : un code est un identifiant court et clos
(`model_unavailable`, `unavailable`), pas de la prose. `NULL` sur tous les jobs
existants, ce qui est juste : aucun n'a de code, et un défaut fabriqué prétendrait
savoir pourquoi un job antérieur a échoué.

`batch_alter_table` est obligatoire sur SQLite, dont l'`ALTER TABLE` ne sait pas tout
faire : Alembic reconstruit la table. Les quatre migrations précédentes l'utilisent déjà.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Les types personnalisés du projet sont rendus par Alembic avec leur chemin
# complet : sans cet import, la migration lève un NameError à l'exécution.
import traffic_analysis.core.db.types  # noqa: F401

revision: str = "209be6775284"
down_revision: str | None = "c3ae6ba3917c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("error_code", sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_column("error_code")

    # ### end Alembic commands ###
