"""ajoute le texte de plaque

Revision ID: c3ae6ba3917c
Revises: a39ceb36f745
Create Date: 2026-08-06 15:15:15.544471

`plate_text` en `String(16)` : la normalisation du domaine plafonne à dix
alphanumériques plus leurs séparateurs, donc seize laisse de la marge sans être une
invitation. `NULL` signifie « aucune lecture concluante » et se distingue de `''`.

Un index sur `(job_id, plate_text)` pour le registre, **aucun** pour les
franchissements : ceux-ci se lisent par ligne et par temps, jamais par plaque.

`batch_alter_table` est obligatoire sur SQLite, dont l'`ALTER TABLE` ne sait pas tout
faire : Alembic reconstruit la table. Les trois migrations précédentes l'utilisent déjà.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Les types personnalisés du projet sont rendus par Alembic avec leur chemin
# complet : sans cet import, la migration lève un NameError à l'exécution.
import traffic_analysis.core.db.types  # noqa: F401

revision: str = "c3ae6ba3917c"
down_revision: str | None = "a39ceb36f745"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("job_crossings", schema=None) as batch_op:
        batch_op.add_column(sa.Column("plate_text", sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column("plate_text_score", sa.Float(), nullable=True))

    with op.batch_alter_table("job_vehicles", schema=None) as batch_op:
        batch_op.add_column(sa.Column("plate_text", sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column("plate_text_score", sa.Float(), nullable=True))
        batch_op.create_index("ix_job_vehicles_plate_text", ["job_id", "plate_text"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("job_vehicles", schema=None) as batch_op:
        batch_op.drop_index("ix_job_vehicles_plate_text")
        batch_op.drop_column("plate_text_score")
        batch_op.drop_column("plate_text")

    with op.batch_alter_table("job_crossings", schema=None) as batch_op:
        batch_op.drop_column("plate_text_score")
        batch_op.drop_column("plate_text")

    # ### end Alembic commands ###
