"""ajoute la table geometry_presets

Revision ID: a39ceb36f745
Revises: 8a64414a3f3b
Create Date: 2026-08-06 07:30:49.483632
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Les types personnalisés du projet sont rendus par Alembic avec leur chemin
# complet : sans cet import, la migration lève un NameError à l'exécution.
import traffic_analysis.core.db.types

revision: str = "a39ceb36f745"
down_revision: str | None = "8a64414a3f3b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "geometry_presets",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("source_width", sa.Integer(), nullable=False),
        sa.Column("source_height", sa.Integer(), nullable=False),
        sa.Column("mask_outside_zones", sa.Boolean(), nullable=False),
        sa.Column("lines_json", sa.Text(), nullable=False),
        sa.Column("zones_json", sa.Text(), nullable=False),
        sa.Column(
            "created_at", traffic_analysis.core.db.types.UtcDateTime(length=32), nullable=False
        ),
        sa.Column(
            "updated_at", traffic_analysis.core.db.types.UtcDateTime(length=32), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("geometry_presets", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_geometry_presets_name"), ["name"], unique=True)
        batch_op.create_index("ix_geometry_presets_updated", ["updated_at"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("geometry_presets", schema=None) as batch_op:
        batch_op.drop_index("ix_geometry_presets_updated")
        batch_op.drop_index(batch_op.f("ix_geometry_presets_name"))

    op.drop_table("geometry_presets")
    # ### end Alembic commands ###
